version: "{build}"

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1"

install:
  - appveyor DownloadFile ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/windows/GraphicsMagick-1.3.19-Q8-win32-dll.exe
  - GraphicsMagick-1.3.19-Q8-win32-dll.exe /SP /VERYSILENT /NORESTART /NOICONS
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
